### ISSUE TITLE
DB Migration

### ISSUE THREAD

**Issue by afikrim** [FemiNoviaLina/bccintern#1]
Ini ada migrationnya nggak ya?

Kalau semisal nggak ada, sertain DDLnya ya, biar nanti bisa dipake untuk define databasenya di server BCC

**Comment by FemiNoviaLina** [comment]
> Ini ada migrationnya nggak ya?
> 
> Kalau semisal nggak ada, sertain DDLnya ya, biar nanti bisa dipake untuk define databasenya di server BCC

Ada kak

**Comment by afikrim** [comment]
Okeoke, auto migrate atau ada command yang harus dipanggil ya?

**Comment by FemiNoviaLina** [comment]
Auto migrate kak

**Comment by afikrim** [comment]
Okeoke, thanks infonya
